name: Purge Cloudflare Cache

on:
  push:
    branches:
      - master # masterブランチへのpush時にトリガー

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge cache
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache \
              -H "Authorization: Bearer $CLOUDFLARE_AUTH_KEY" \
              -d '{"hosts":["oppai.ninja"]}'
